### ISSUE TITLE
RSS Feed not pulling images into Newsletter

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#101]
https://etccooperative.org/rss/feed.en.xml

**Comment by gd8097019** [comment]
Hey @andrewgdick There is no image field in rss. I think every third party software uses their own definition. I saw this comment on [Stackoverflow](https://stackoverflow.com/a/48549541) 

I think you use Mailchimp to Newsletter. I added required definition to RSS. 

Could you check this PR: https://github.com/ETCCooperative/etc-coop-website/pull/110
