### ISSUE TITLE
ETCcooperative.org Technical Requirements

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#2]
**ETCcooperative.org Technical Requirements**

Tech Stack
Built with a Netlify/Github stack & Cloudflare integration

Chinese and English Versions of the site
Toggle between Chinese and English Versions like the Grants Dao site

New Menu & Pages 
Home 
What is Ethereum Classic?
Mining on ETC
Developing for ETC
News/Blogs/Tutorials
Contact
What is ETC Cooperative
- Governance 
- Filings
- People
Contact

**Blog functionality**
Must be able to write blogs in MD form
RSS feed for blogs
Social Media sharing buttons on blog posts
Latest posts on the front page
Blog page with pagination 
SEO - meta information updated for each blog post
Connect RSS to Mailerlite
OpenGraph tags
Ability to make a post “sticky” - stay at the top of the page

**Copy/Updates** 
 All copy should be separated out to MDs for easy updates by non-technical staff
Basic updates should be manageable by non-technical staff

**Newsletter**
Newsletter form signup and integration with Mailerlite
Integrate newsletter & from RSS feed

**Google**
Have Google Analytics and Search Console code on every page header

**Contact Us Form**
Connected to a @etccooperative.org email address

**Comment by bobsummerwill** [comment]
Looks like this is all done?  @andrewgdick
