### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#27]
Please ensure we will have a functional RSS feed for our Blog.

**Comment by gd8097019** [comment]
Hey @andrewgdick we already have custom built-in RSS feed generator in our codebase. You can check this urls:

- https://endearing-frangipane-bf1ae1.netlify.app/rss/feed.en.xml
- https://endearing-frangipane-bf1ae1.netlify.app/rss/feed.cn.xml

also you can check `generateRssFeed.js` how it is generating for every build
