### ISSUE TITLE
FILINGS & GOVERNANCE Page

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#29]
- Please open PDFs & Docs in new page

**Comment by bobsummerwill** [comment]
Where do you click to open the linked PDFs?  Maybe that is not configured yet but it looks like it is clicking on > where it should actually be clicking on the words.

**Comment by gd8097019** [comment]
Hey @andrewgdick check my PR: https://github.com/ETCCooperative/etc-coop-website/pull/38

**Comment by andrewgdick** [comment]
Could we get the PDF icon and the Title Copy to link (blank) to the file, please?  See screenshot:
<img width="1120" alt="Screenshot 2023-07-05 at 10 00 38 AM" src="https://github.com/ETCCooperative/etc-coop-website/assets/974129/4ff99fda-0f80-4013-9b91-1659204453f5">

**Comment by gd8097019** [comment]
Hey @andrewgdick I fixed and merged. Check the current website: https://endearing-frangipane-bf1ae1.netlify.app/filings
