### ISSUE TITLE
News/Blogs Page Design Page layout 

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#30]
- The top of this  page should look like a subpage (I have a header image ready) 
- with the blog content like the front page (like in the Figma) 
- followed by "Newsletter sign up" then the "footer"

**Comment by gd8097019** [comment]
Hey @andrewgdick check my PR for this issue: https://github.com/ETCCooperative/etc-coop-website/pull/43

You can test the page `/news` url

**Comment by gd8097019** [comment]
Pull request url updated: https://github.com/ETCCooperative/etc-coop-website/pull/46
