### ISSUE TITLE
Metadata / Google Analytics / Search Console 

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#33]
**Google Analytics:**

<script async src="https://www.googletagmanager.com/gtag/js?id=G-6KRRF01CTG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-6KRRF01CTG');
</script>

**Search Console:**
<meta name="google-site-verification" content="4QT8FZgSNNywdOcRc92DaMwcCXfakiN28bI6pSTPNEo" />

**OG/Metadata:**

<title>ETC Cooperative</title>
<meta name="description" content="ETC Cooperative - Our mission is to steward the development of the Ethereum Classic protocol "/>
<meta property="og:url" content="https://etccooperative.org/"/>
<meta property="og:type" content="website"/>
<meta property="og:title" content="ETC Cooperative"/>
<meta property="og:site_name" content="ETC Cooperative"/>
<meta property="og:description" content="Supporting ETC Development & Ecosystem"/>
<meta property="og:image" content="https://etccooperative.org/img/social.png"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta property="twitter:domain" content="etccooperative.org"/>
<meta property="twitter:url" content="https://etccooperative.org/"/>
<meta name="twitter:title" content="ETC Cooperative"/>
<meta name="twitter:description" content="ETC Cooperative - Supporting ETC Development & Ecosystem."/>
<meta name="twitter:image" content="https://etccooperative.org/img/social.png"/>

**Comment by gd8097019** [comment]
Hey @andrewgdick check my PR for this issue: https://github.com/ETCCooperative/etc-coop-website/pull/41
