### ISSUE TITLE
Short Descriptions for Board members 

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#35]

**Comment by andrewgdick** [comment]
Please add these descriptions to the PEOPLE page

Board Descriptions

Roy Zou
Engineer, founder of Gödel Labs (哥德尔实验室). 

Cody Burns
Technology and Innovation Leader | Driving growth and transformation strategy through emerging technologies, Ethereum expertise, and metaverse capabilities.

Craig Salm
Chief Legal Officer at Grayscale Investments, the world’s largest digital currency asset manager.

**Comment by gd8097019** [comment]
Hey @andrewgdick I just created and merged PR. Please check current website.

**Comment by andrewgdick** [comment]
The descriptions are in that old blue/black. Can you update them with the new colour, please?

**Comment by gd8097019** [comment]
Hey @andrewgdick I updated all colors depend on figma. You can check description area and also all website

**Comment by andrewgdick** [comment]
@bobsummerwill , we still need a short one-line blurb for Elaine Ou

**Comment by bobsummerwill** [comment]
Sent email.

**Comment by bobsummerwill** [comment]
"Engineer at Global Financial Access"
