### ISSUE TITLE
Refresh blogs

### ISSUE THREAD

**Issue by bobsummerwill** [ETCCooperative/etc-coop-website#44]
Please can you refresh the blogs - bringing a batch of new posts across from the existing site?

We've had the same images for two months and it is hard to judge how things look with the same content all the time.   The current large highlighted one's image is slightly odd looking, for example.

Thanks!

**Comment by gd8097019** [comment]
Hey @bobsummerwill and @andrewgdick I refreshed all blog posts. You can check demo website: 

https://endearing-frangipane-bf1ae1.netlify.app/
