### ISSUE TITLE
Link colours

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#50]
1) Light mode - Footer - mouse-over is white please change it to mid green 
2) Light mode - Footer - link colour is grey/blue please use grey/green

**Comment by gd8097019** [comment]
Hey @andrewgdick I am fixed for hover problem in 1. but I could not understand 2 ? Could you describe more:

`Light mode - Footer - link colour is grey/blue please use grey/green`

**Comment by gd8097019** [comment]
Hey @andrewgdick its updated please check current website
