### ISSUE TITLE
Pagination Styling

### ISSUE THREAD

**Issue by andrewgdick** [ETCCooperative/etc-coop-website#51]
The pagination links at the bottom of the blog need to use the site's colours

<img width="562" alt="Screenshot 2023-07-05 at 10 12 44 AM" src="https://github.com/ETCCooperative/etc-coop-website/assets/974129/597d434e-cb95-48fc-b1fa-4422904391da">

**Comment by gd8097019** [comment]
Hey @andrewgdick I updated main website please check: https://endearing-frangipane-bf1ae1.netlify.app/news
