### ISSUE TITLE
Please can you ensure that tables look good enough in the MD blog files

### ISSUE THREAD

**Issue by bobsummerwill** [ETCCooperative/etc-coop-website#73]
See https://www.markdownguide.org/extended-syntax/

We should be able to create tables within our blog MD files and they should look not terrible.

Please can you test this out?  We just tried it in our existing website but the borders are missing in the rendering so it looks pretty awful.

Thanks!

**Comment by gd8097019** [comment]
Hey @bobsummerwill I added table to current MD files. It rendered like that: 

<img width="234" alt="Screenshot 2023-07-20 at 14 09 43" src="https://github.com/ETCCooperative/etc-coop-website/assets/102132498/4cecf137-0177-4084-a261-5722b71b2a0b">

<img width="250" alt="Screenshot 2023-07-20 at 14 09 38" src="https://github.com/ETCCooperative/etc-coop-website/assets/102132498/9994913d-f3d9-4f28-b2a9-294f1f0a06e1">

But I added css rules and right now you can use it 

<img width="675" alt="Screenshot 2023-07-20 at 14 16 08" src="https://github.com/ETCCooperative/etc-coop-website/assets/102132498/1bd8e2e4-38ec-4e7f-9807-4491a41694e1">

**Comment by bobsummerwill** [comment]
Great - thank you!
