### ISSUE TITLE
The dates are incorrect for recent blog posts

### ISSUE THREAD

**Issue by bobsummerwill** [ETCCooperative/etc-coop-website#88]
https://etccooperative.org/posts/2023-08-01-bob-summerwill-will-be-speaking-at-the-5th-annual-blockchain-futurist-conference-cn - Shows July 01, 2023

https://etccooperative.org/posts/2023-07-31-presenting-first-round-etc-grants-dao-winner-hebeswap-oracle-cn - shows July 00, 2023

**Comment by gd8097019** [comment]
Related PR: https://github.com/ETCCooperative/etc-coop-website/pull/121

**Comment by bobsummerwill** [comment]
This fix is better, but still not quite right.
It looks like there is probably a timezone issue remaining.

So this article is dated August 8th (today) ...

https://etccooperative.org/posts/2023-08-08-presenting-first-round-etc-grants-dao-winner-ETC-Fans-en

... but the date showing on the article page itself is August 7th.

**Comment by bobsummerwill** [comment]
Great - thanks for that!
