### ISSUE TITLE
Social Media cards not showing for posts, especially Chinese ones.

### ISSUE THREAD

**Issue by DonaldMcIntyre** [ETCCooperative/etc-coop-website#99]
I tried this link on Discord and it shows the social media card for the EN version, but not CN. It shows a "null" message for CN.

https://etccooperative.org/posts/2023-08-01-bob-summerwill-will-be-speaking-at-the-5th-annual-blockchain-futurist-conference-en

Then I tried it on Twitter and it shows the same "null" message for the CN version, but also doesn't show anything for the EN version.

On Facebook both show the card for the website but not for the post, but when you click it takes you to the post.

On LinkedIn it does the same as Facebook.

**Comment by gd8097019** [comment]
Hey @DonaldMcIntyre and @andrewgdick you need to open some settings on Netlify admin panel to render metadata.

![netlify](https://github.com/ETCCooperative/etc-coop-website/assets/102132498/42802a32-2fd9-411b-a038-f000a46ab9c0)
